### ISSUE TITLE
Failing stack creation on certain error codes.

### ISSUE THREAD

**Issue by sriram9707** [aws-quickstart/qs-cfn-lint-rules#13]
Hi,

We have developed a cicd pipeline for creating resources through cfn. As a security checks, we use cfn-lint and cfn-nag for testing the templates. Is there any flags to pass so that we can fail the build if certain error codes met ?

**Comment by andrew-glenn** [comment]
@sriram9707 

These are custom cfn-linting rules for our team's use. For a CFN-based testing tool, please see aws-quickstart/taskcat :)

cfn-lint/cfn-nag expose exit codes you can surface to your pipeline. Beyond that, I'm uncertain what you're asking :)
